test commit
North-Seattle-College/ad440-winter2021-thursday-repo pull request #139
Opened 2021-02-09 02:29 UTC by David-Prism

2021-02-11 04:27 UTC, farhadbahrehmandhenry approved these changes

2021-02-11 08:57 UTC, David-Prism commented
DATE | ACTIVITY | TIME
-- | -- | --
02/05 | Pair programming with Farhad to work through similar issues | 60 minutes
02/08 | Created a PR for a test version of the task | 20 minutes
02/08 | Worked with Farhad and Jenny | 120 minutes
02/10 | Created an issue (#146), linked to the PR, updated PR | 20 minutes
02/10 | Worked with Farhad on our issues, repeated "test run" process with the actual function app | 190 minutes

2021-02-11 22:40 UTC, theKunte approved these changes

2021-02-12 03:19 UTC, farhadbahrehmandhenry requested changes
I believe you should rename the deployAzureFunctions.yaml file to deploy-apis.yml according to the lecture.

2021-02-15 22:44 UTC, theKunte requested changes
Same as Farhad comment

2021-02-17 04:41 UTC, farhadbahrehmandhenry approved these changes

2021-02-17 04:45 UTC, theKunte approved these changes

2021-02-17 04:45 UTC, merged