all changes
North-Seattle-College/ad440-winter2021-thursday-repo pull request #173
Opened 2021-02-18 07:44 UTC by jaguiniga

Added connection to Redis Server and pull Task ID data from DB and dump in Redis Cash

2021-02-18 19:09 UTC, StopMakingUsernamesUnique requested changes
Remove hard-coded password

2021-02-18 23:07 UTC, chonger878 reviewed
Just curious, are you planning on making the host and port a secret/environment variable?  I know the password has to be one.

2021-02-20 06:55 UTC, chonger878 approved these changes

2021-02-20 18:31 UTC, StopMakingUsernamesUnique approved these changes

2021-02-20 19:48 UTC, unicornsleuth commented on functions/HttpTriggerAPIUsersIdTaskId/__init__.py
> +r.set("Message01", "Hello World")
You can delete this

2021-02-20 19:54 UTC, unicornsleuth requested changes
I couldn't get this to work with {{ secrets.ENV_REDIS_KEY }} but if it works for you, okay.
I did get this failure though! I think you will need to convert the datetime fields to strings to make caching work, but you may be able to find another workaround.

2021-02-25 05:48 UTC, toddysm commented on functions/HttpTriggerAPIUsersIdTaskId/__init__.py
> +port=6380, db=0, password= '${{ secrets.ENV_REDIS_KEY }}', ssl=True)
Where this secret comes from?

2021-03-11 09:03 UTC, jaguiniga commented on functions/HttpTriggerAPIUsersIdTaskId/__init__.py
> +port=6380, db=0, password= '${{ secrets.ENV_REDIS_KEY }}', ssl=True)
I fixed it, not a secret but os.ENVIRON

2021-03-11 21:45 UTC, merged