Redis Expire on get + rDB bug + redisfeatureflag
North-Seattle-College/ad440-winter2021-thursday-repo pull request #218
Opened 2021-02-28 22:40 UTC by StopMakingUsernamesUnique

Redis Cache now expires on get requests, bug regarding the rDB not being passed to add_tasks method is fixed, redisfeatureflag now exists as CACHE_TOGGLE.

2021-02-28 23:13 UTC, zxkevinxz requested changes
Redis password line needs to be changed back.

2021-02-28 23:13 UTC, zxkevinxz commented on functions/HttpTriggerAPIUsersIdTask/__init__.py
> +            rDB = redis.Redis(host='nsc-redis-dev-usw2-thursday.redis.cache.windows.net', port='6380', db=0, password='${{ secrets.ENV_REDIS_KEY }}', ssl=True)
the password needs to be os.environ["ENV_REDIS_KEY"], '${{ secrets.ENV_REDIS_KEY }}' is a reference to the github repo secrets.

2021-02-28 23:25 UTC, farhadbahrehmandhenry commented on functions/HttpTriggerAPIUsersIdTask/__init__.py
>          return func.HttpResponse(json.dumps({task_id}, default=default), status_code=200, mimetype="application/json")
currently, it's not returning taskId in a correct format. should be =>
return func.HttpResponse(json.dumps({"taskId": task_id}), status_code=200, mimetype="application/json")

2021-03-04 03:59 UTC, jaguiniga approved these changes
The hard coded information was taken out and it connects to docker server and gets an the array when connected to the SQl DB

2021-03-04 19:35 UTC, merged