React UI
North-Seattle-College/ad440-winter2021-thursday-repo pull request #38
Opened 2021-01-15 02:49 UTC by David-Prism

Basic boilerplate react UI.

2021-01-15 05:13 UTC, theKunte commented on functions/.vscode/extensions.json
> +}
We might need to remove all of the .vsode files from our folder. I think in toddy's lecture he recommended to move these files into the .gitignor file. 

PS: Jak create the entire file structure for our team

2021-01-15 06:34 UTC, farhadbahrehmandhenry reviewed
as you can see there are a lot of changed files in your branch that is not related to the feature you added. if we merge this branch we actually have merged some unfinished features. I don't know if it's ok or not.
also you probably need to add a documentation to your PR too explaining how to run the app you created.

2021-01-16 21:54 UTC, toddysm commented
As @theKunte and @farhadbahrehmandhenry noted above, there are a lot of files that should not be committed to the repo. Also, avoid cluttering the repo with `test` files.

2021-01-24 00:53 UTC, David-Prism commented
## To run the app, run the commands:
-Navigate to the ui folder, then the react-ui folder
-Run `npm install`
-Run `npm start`

2021-01-24 00:58 UTC, farhadbahrehmandhenry approved these changes

2021-01-24 01:05 UTC, theKunte commented
npm install and npm start works and I was able to run it on my machine.

2021-01-24 01:06 UTC, theKunte approved these changes

2021-01-24 01:43 UTC, theKunte requested changes
Actually, I was not able to run the react app

2021-01-24 01:46 UTC, theKunte approved these changes
Never mind :D 
I was able to run the app after navigating to the react-ui folder
![image](https://user-images.githubusercontent.com/32443542/105619007-ec91df00-5da2-11eb-9868-1945d4bec521.png)

2021-01-25 01:50 UTC, closed without merging