Created a script that creates public ip address.
North-Seattle-College/ad440-winter2021-thursday-repo pull request #43
Opened 2021-01-16 06:46 UTC by natni

2021-01-16 22:13 UTC, toddysm requested changes
Also, assign people as reviewers

2021-01-16 22:13 UTC, toddysm commented on example/Automation/create_ip_address.ps1
> +$zone = 2
What does `$zone=2` mean? Comments in your code will also be helpful.

2021-01-17 05:20 UTC, natni commented
Thanks for the feedback. I have updated the script based on the recommendations.

2021-01-18 08:29 UTC, natni commented
**Description**
Closes #41 

**This PR holds a script that creates a Public IP Address in Azure** 
You should be careful about what you enter on the prompts when creating Public IP. Enter a correct resource group that exists, a proper location eg. 'eastus2', a proper public address name, SKU type eg. 'Standard' and a proper allocation method eg 'static' 

How to test:
1. Run the script while on the file directory by writing _./create_ip_address.ps1_
2. Enter inputs for the params: _rgname_, _location_, _publicIp_, _sku_ and _allocation_.

2021-01-19 02:54 UTC, unicornsleuth requested changes

2021-01-19 02:54 UTC, unicornsleuth commented on Automation/create_ip_address.ps1
> +New-AzPublicIpAddress -ResourceGroupName $rgname -Name $publicIp -Location $location -AllocationMethod $allocation -SKU $sku
We don't want there to be any user interaction/prompting, so the directions should say to add all of it on the same line, like 
`./Automation/create_ip_address.ps1 -rgname test-natanaels-pr-ly -location "uksouth" -publicIp "ip-address-test-ly" -sku Basic -allocation Dynamic`

Also consider doing some checks on the resource group, have it create a new rg if that one doesn't already exist
You will get errors if you try to create an IP address with a location that doesn't match the RG, so you can use the same location for both.

2021-01-21 06:00 UTC, unicornsleuth requested changes

2021-01-21 06:00 UTC, unicornsleuth commented on Automation/create_ip_address.ps1
> +## Command to create a public ip ##
Do we need this file? Not sure which is the final/correct version of the script

2021-01-21 06:00 UTC, unicornsleuth commented on Automation/public_ip_template.json
> +{
Same with this - pretty sure just needs to be deleted

2021-01-21 06:28 UTC, natni commented
For some reason, I didn't save my code on VS Code before pushing and it just pushed stuff I already modified and deleted. I'm pushing a new one now

2021-01-21 08:16 UTC, unicornsleuth reviewed
It successfully created the IP address! Looking great - just a couple small comments and then you're good!

2021-01-21 08:16 UTC, unicornsleuth commented on Automation/PublicIP/public_ip_template.json
> +            "location": "westus2",
Shouldn't this be [parameters('location')]  ?

2021-01-21 08:16 UTC, unicornsleuth commented on Automation/PublicIP/public_ip_template.json
> +                "ipAddress": "20.69.187.53",
hard-coded value?

2021-01-21 08:16 UTC, unicornsleuth commented on Automation/PublicIP/create_ip_address.ps1
> +        [string] [Parameter(Mandatory=$true)] $rgname, # Name of the resource group
I think Toddy said to use longer, descriptive variable names, so he'd prefer resourceGroupName. We should check if he wants camel case or all the first letters capitalized, but low priority

2021-01-22 03:50 UTC, unicornsleuth approved these changes
Everything looks good and works as expected! When I first tried, I put in a new resource group and it didn't create anything, but the error was handled smoothly, and when I selected a rg that already existed, it worked perfectly! : )

2021-01-26 21:45 UTC, toddysm approved these changes

2021-01-26 22:29 UTC, merged