pull request due to sprint 1
North-Seattle-College/ad440-winter2021-thursday-repo pull request #65
Opened 2021-01-21 06:59 UTC by jinudean

pull request for testing and reviewing purpose

2021-01-21 07:00 UTC, jinudean commented
first pull request due to sprint 1

2021-01-22 00:56 UTC, zxkevinxz requested changes

2021-01-22 00:56 UTC, zxkevinxz commented on Automation/createresource.ps1
> +$storageAccountName = Read-Host -Prompt "Enter the storage account name"
This could be better if taken in as parameters instead of prompts so whoever runs it can just do it in one line.

2021-01-22 00:56 UTC, zxkevinxz commented on Automation/createresource.ps1
> +  -SkuName "Standard_LRS"
Should this SkuName be hardcoded? Maybe a parameter with a default value?

2021-01-22 03:49 UTC, closed without merging